language: rust
rust: nightly
cache: cargo

branches:
  # don't rerun after tagging releases
  except:
    - /^v[0-9]+\.[0-9]+\.[0-9]+/

script:
  - |
      cargo build &&
      cargo test &&
      cargo bench

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_PULL_REQUEST = "false"
    script: scripts/deploy.sh
