[package]
name = "sc2"
version = "0.1.0"
authors = ["najen"]

[dependencies]
bytes = "0.4"
futures = "0.1"
futures-cpupool = "0.1"
protobuf = "1.3"
tokio-timer = "0.1"
ws = "0.7.3"
sc2-proto = { git = "https://github.com/awestlake87/sc2-proto-rs" }
