[package]
name = "sc2"
version = "0.1.0"
authors = ["najen"]

[dependencies]
bytes = "*"
futures-await = { git = "https://github.com/alexcrichton/futures-await" }
glob = "*"
glutin = "*"
nalgebra = "*"
protobuf = "*"
rand = "*"
regex = "*"
sc2-proto = { git = "https://github.com/awestlake87/sc2-proto-rs" }
tokio-core = "0.1.9"
tungstenite = "0.4.0"
url = "*"

[workspace]
members = ["examples/examples-common"]

[[example]]
name = "bot-simple"
crate-type = ["bin"]
path = "examples/bot-simple/main.rs"

[dev-dependencies]
docopt = "0.8"
examples-common = { path = "examples/examples-common" }
