[package]
name = "sc2"
version = "0.2.0"
authors = ["najen"]

[dependencies]
bytes = "*"
ctrlc = "*"
error-chain = "*"
futures = "*"
glob = "*"
nalgebra = "*"
protobuf = "*"
rand = "*"
regex = "*"
sc2-proto = { git = "https://github.com/awestlake87/sc2-proto-rs" }
tokio-core = "*"
tokio-timer = "*"
tokio-tungstenite = "*"
tungstenite = "*"
url = "*"
uuid = { version = "*", features = ["serde", "v4"] }

[dependencies.organelle]
git = "https://github.com/awestlake87/organelle"
branch = "reactive"

[workspace]
members = ["examples/examples-common"]

[[example]]
name = "bot-micro"
crate-type = ["bin"]
path = "examples/bot-micro/main.rs"

[[example]]
name = "bot-mp"
crate-type = ["bin"]
path = "examples/bot-mp/main.rs"

[dev-dependencies]
docopt = "0.8"
glutin = "*"
examples-common = { path = "examples/examples-common" }
