[package]
name = "sc2"
version = "0.1.0"
authors = ["najen"]

[dependencies]
bytes = "*"
ctrlc = "*"
error-chain = "*"
futures = "*"
glob = "*"
nalgebra = "*"
protobuf = "*"
rand = "*"
regex = "*"
sc2-proto = { git = "https://github.com/awestlake87/sc2-proto-rs" }
tokio-core = "*"
tokio-tungstenite = "*"
tungstenite = "*"
url = "*"

[dependencies.cortical]
git = "https://github.com/awestlake87/cortical"
branch = "reactive"

[workspace]
members = ["examples/examples-common"]

[[example]]
name = "bot-micro"
crate-type = ["bin"]
path = "examples/bot-micro/main.rs"

[[example]]
name = "bot-mp"
crate-type = ["bin"]
path = "examples/bot-mp/main.rs"

[[example]]
name = "bot-simple"
crate-type = ["bin"]
path = "examples/bot-simple/main.rs"

[[example]]
name = "debug"
crate-type = ["bin"]
path = "examples/debug/main.rs"

[[example]]
name = "replay"
crate-type = ["bin"]
path = "examples/replay/main.rs"

[[example]]
name = "reactive"
crate-type = ["bin"]
path = "examples/reactive/main.rs"

[dev-dependencies]
docopt = "0.8"
glutin = "*"
examples-common = { path = "examples/examples-common" }
