[package]
name = "nuro-sc2"
version = "0.1.0"
authors = ["najen"]

[dependencies]
bytes = "0.4"
futures = "0.1"
futures-cpupool = "0.1"
nuro-sc2-proto = { path = "./nuro-sc2-proto" }
protobuf = "1.3"
tokio-timer = "0.1"
ws = "0.7.3"
