[package]
name = "sc2"
version = "0.1.1"
authors = ["Andrew J Westlake <kelixes@gmail.com>"]
description = "organelle networks for StarCraft II Client API"
license = "MIT"
license-file = "LICENSE.md"
documentation = "https://docs.rs/sc2-rs"
homepage = "https://github.com/awestlake87/sc2-rs"
repository = "https://github.com/awestlake87/sc2-rs"

[dependencies]
bytes = "0.4"
ctrlc = "3.0"
error-chain = "0.11"
futures = "0.1"
glob = "0.2"
nalgebra = "0.13"
organelle = "0.1"
protobuf = "1.4"
rand = "0.4"
regex = "0.2"
sc2-proto = "0.1"
tokio-core = "0.1"
tokio-timer = "0.1"
tokio-tungstenite = "0.5"
tungstenite = "0.5"
url = "1.6"
uuid = { version = "0.5", features = ["serde", "v4"] }

[workspace]
members = ["examples/examples-common"]

[[example]]
name = "bot-micro"
crate-type = ["bin"]
path = "examples/bot-micro/main.rs"

[[example]]
name = "bot-mp"
crate-type = ["bin"]
path = "examples/bot-mp/main.rs"

[dev-dependencies]
docopt = "0.8"
examples-common = { path = "examples/examples-common" }
