[package]
name = "sc2"
version = "0.1.0"
authors = ["najen"]

[dependencies]
futures = "*"
sc2-proto = { git = "https://github.com/awestlake87/sc2-proto-rs" }
tokio-core = "*"
tokio-timer = "*"
tokio-tungstenite = "*"
tungstenite = "0.4.0"
url = "*"
